version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_instance
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}
    # command: mongod --bind_ip_all
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    restart: always
    container_name: cpen321_app
    environment:
      - DB_URI=${DB_URI}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
      - "4242:4242"
    depends_on:
      - mongo
    command: npm start

volumes: 
  mongo_data: