version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_instance
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    restart: always
    container_name: cpen321_app
    environment:
      - DB_URI=${DB_URI}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    command: npm start

  rasa:
    image: rasa/rasa:latest
    container_name: rasa_bot
    restart: always
    volumes:
      - ./Backend/rasa_bot:/app  
    ports:
      - "5005:5005"
    command:
      - run
      - --enable-api
      - --debug
    depends_on:
      - mongo

  rasa-actions:
    image: rasa/rasa-sdk:latest
    container_name: rasa_action_server
    restart: always
    volumes:
      - ./Backend/rasa_bot/actions:/app/actions  
    ports:
      - "5055:5055"
    command:
      - start
    depends_on:
      - rasa

volumes: 
  mongo_data:
