version: "3.1"
recipe: default.v1
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: LexicalSyntacticFeaturizer
- name: RegexEntityExtractor
  use_lookup_tables: True
  use_regexes: True
  use_word_boundaries: False 
- name: DIETClassifier
  epochs: 100
  entity_recognition: True
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.6  
  ambiguity_threshold: 0.2 
