version: "3.1"

recipe: default.v1

language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: LexicalSyntacticFeaturizer
- name: RegexEntityExtractor
  use_lookup_tables: True
  use_regexes: True

- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.6  
  ambiguity_threshold: 0.2  
policies:
- name: AugmentedMemoizationPolicy  
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100

assistant_id: 20250221-133337-careful-swing
