version: "3.1"
recipe: default.v1
language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: LexicalSyntacticFeaturizer
- name: RegexEntityExtractor
  use_lookup_tables: true
  use_regexes: true
  use_word_boundaries: false
  case_sensitive: false
  match_word_boundaries: false
- name: DIETClassifier
  epochs: 100
  entity_recognition: true
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.6
  ambiguity_threshold: 0.2
assistant_id: 20250310-154626-absolute-chow