name: Auto Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  auto-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd Backend
          npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'

      - name: Run Tests with Secrets
        env:
            FIREBASE_CONFIG: ${{ secrets.GOOGLE_CLOUD_KEY_FIREBASE }} 
            STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
            SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
            TEST_GOOGLE_TOKEN: ${{ secrets.TEST_GOOGLE_TOKEN }}
            GOOGLE_NUM_ID: ${{ secrets.GOOGLE_NUM_ID }}
            OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
            GOOGLE_USER_ID: ${{secrets.GOOGLE_USER_ID}}
            GOOGLE_USER_PREFIX: ${{ secrets.GOOGLE_USER_PREFIX }}
            PUBLISHABLE_STRIPE_KEY: ${{ secrets.PUBLISHABLE_STRIPE_KEY }}
        run: |
            cd Backend
            NODE_ENV=test npm test